package com.cjc.contact.service.impl;

import com.cjc.contact.dto.ContactDTO;
import com.cjc.contact.entity.ContactEntity;
import com.cjc.contact.exception.ContactNotFoundException;
import com.cjc.contact.repository.ContactRepository;
import com.cjc.contact.service.ContactService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;


@Service
@Transactional
public class ContactServiceImpl implements ContactService {

    private final ContactRepository contactRepository;

    public ContactServiceImpl(ContactRepository contactRepository) {
        this.contactRepository = contactRepository;
    }

    @Override
    public ContactDTO createContact(ContactDTO contactDTO) {
        ContactEntity entity = mapToEntity(contactDTO);
        // Ensure ID is generated by database auto-increment
        entity.setId(null);
        ContactEntity savedEntity = contactRepository.save(entity);
        return mapToDTO(savedEntity);
    }

    @Override
    @Transactional(readOnly = true)
    public List<ContactDTO> getAllContacts() {
        return contactRepository.findAll()
                .stream()
                .map(this::mapToDTO)
                .collect(Collectors.toList());
    }

    @Override
    @Transactional(readOnly = true)
    public ContactDTO getContactById(Long id) {
        ContactEntity entity = contactRepository.findById(id)
                .orElseThrow(() -> new ContactNotFoundException("Contact not found with ID: " + id));
        return mapToDTO(entity);
    }

    @Override
    public ContactDTO updateContact(Long id, ContactDTO contactDTO) {
        ContactEntity existingEntity = contactRepository.findById(id)
                .orElseThrow(() -> new ContactNotFoundException("Cannot update. Contact not found with ID: " + id));

        existingEntity.setName(contactDTO.getName());
        existingEntity.setEmail(contactDTO.getEmail());
        existingEntity.setPhone(contactDTO.getPhone());
        existingEntity.setCategory(contactDTO.getCategory());

        ContactEntity updatedEntity = contactRepository.save(existingEntity);
        return mapToDTO(updatedEntity);
    }

    @Override
    public void deleteContact(Long id) {
        if (!contactRepository.existsById(id)) {
            throw new ContactNotFoundException("Cannot delete. Contact not found with ID: " + id);
        }
        contactRepository.deleteById(id);
    }

    private ContactDTO mapToDTO(ContactEntity entity) {
        return new ContactDTO(
                entity.getId(),
                entity.getName(),
                entity.getEmail(),
                entity.getPhone(),
                entity.getCategory()
        );
    }

    private ContactEntity mapToEntity(ContactDTO dto) {
        return new ContactEntity(
                dto.getId(),
                dto.getName(),
                dto.getEmail(),
                dto.getPhone(),
                dto.getCategory()
        );
    }
}
